services:
  dask-notebook:
    build:
      context: ../../../ # Expandindo o contexto para a raiz do projeto (Git/)
      dockerfile: devcontainers/.devcontainer/dask_ollama/Dockerfile
    container_name: dask_jupyter_notebook
    ports:
      - "8888:8888"  # Porta Jupyter
      - "8787:8787"  # Porta Dask
    volumes:
      - $HOME/Git:/home/jovyan/Git
      - $HOME/.ssh:/home/jovyan/.ssh